extends:
  - airbnb-base
  - plugin:react/recommended
env:
  jest: true
  browser: true
  node: true
parser: babel-eslint
rules:
  "max-len": [1, 80, 2],
  "object-curly-newline": "never"
globals:
  request: true
